on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
jobs:
  execute-scan-workflow:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:
      eid: f9e9c9dc-fea5-4afe-ac76-b6fedd2d97d6
      oid: 1b7cb377-908d-4440-8f45-14562718b071
      app-name: threat-matrix-2
      trx-host: http://sca.darkeyescan.com
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.TRX_API_KEY }}
